services:
  postgres:
    image: postgres:16-alpine
    container_name: crud_api_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_api_dev
    volumes:
      - crud_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crud-network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crud_api_pgadmin
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - crud_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crud-network


networks:
  crud-network:
    driver: bridge


volumes:
  crud_postgres_data:
  crud_pgadmin_data: